---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KraKss.
--- DateTime: 05/07/2023 16:02
---

fx_version "cerulean"
game "gta5"

author "KraKss"
description "KraKss' Radio V2 - Created for VIBE - DEV"
version "1.0"
lua54 "yes"

shared_scripts {"shared/config.lua"}

client_scripts {
    "RageUI/RMenu.lua",
    "RageUI/menu/RageUI.lua",
    "RageUI/menu/Menu.lua",
    "RageUI/menu/MenuController.lua",
    "RageUI/components/*.lua",
    "RageUI/menu/elements/*.lua",
    "RageUI/menu/items/*.lua",
    "RageUI/menu/panels/*.lua",
    "RageUI/menu/windows/*.lua",
    "lang/*.lua",
    "client/class.lua",
    "client/openRadio.lua"
}

server_scripts {
    "@oxmysql/lib/MySQL.lua", -- oxmysql or mysql or mysql-async
    "server/sv.lua"
}