---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KraKss.
--- DateTime: 10/07/2023 15:59
---

Lang = Lang or {}
Lang["en"] = {
    ["enableRadio"] = "Turn on/off",
    ["radioOn"] = "~g~On",
    ["radioOff"] = "~r~Off",
    ["enableMicClicks"] = "Turn mic clicks on/off",
    ["micClickOn"] = "~g~On",
    ["micClickOff"] = "~r~off",
    ["volumeSlider"] = "Volume (~b~%s%%~s~)",
    ["volumeTextEntry"] = "Volume:",
    ["connectToFrequency"] = "Connect to a frequency",
    ["frequencyTextEntry"] = "Frequency:",
    ["currentFrequency"] = "Current : ~b~%i",
    ["displayEmptyFrequencies"] = "Display empty frequencies",
    ["noPublicFrequencies"] = "No public frequencies available",
    ["frequencyIsJobRestricted"] = "[~r~ERROR~s~]\nThis frequency is restricted to jobs. You may join it from the job menu",
    ["leaveCurrentFrequency"] = "Leave the current frequency",
    ["publicFrequencies"] = "Public frequencies",
    ["jobFrequencies"] = "Job frequencies",
    ["publicFrequencyNumber"] = "Frequency ~b~N°%s",
    ["joinedFrequency"] = "[~g~INFO~s~]\nJoined frequency N°~b~%s",
    ["leftFrequency"] = "[~g~INFO~s~]\nYou left your current frequency",
    ["noItem"] = "[~r~ERROR~s~]\nYou do not have a radio",
    ["frequencyMaxedOut"] = "[~r~ERROR~s~]\nThis frequency is at it's maximum user limit"
}