---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KraKss.
--- DateTime: 10/07/2023 15:59
---

Lang = Lang or {}
Lang["fr"] = {
    ["enableRadio"] = "Allumer/Eteindre la radio",
    ["radioOn"] = "~g~Allumé",
    ["radioOff"] = "~r~Eteint",
    ["enableMicClicks"] = "Activer/Désactiver les bruitages",
    ["micClickOn"] = "~g~Activé",
    ["micClickOff"] = "~r~Désactivé",
    ["volumeSlider"] = "Volume (~b~%s%%~s~)",
    ["volumeTextEntry"] = "Volume:",
    ["connectToFrequency"] = "Se connecter à une fréquence",
    ["frequencyTextEntry"] = "Fréquence :",
    ["leaveCurrentFrequency"] = "Se déconnecter de la fréquence",
    ["publicFrequencies"] = "Fréquences publiques",
    ["jobFrequencies"] = "Fréquences privées",
    ["currentFrequency"] = "Actuelle : ~b~%i",
    ["displayEmptyFrequencies"] = "Afficher les fréquences vide",
    ["noPublicFrequencies"] = "Aucune fréquences publique",
    ["frequencyIsJobRestricted"] = "[~r~ERREUR~s~]\nCette fréquence est réservée aux jobs",
    ["publicFrequencyNumber"] = "Fréquence ~b~N°%s",
    ["joinedFrequency"] = "[~g~INFO~s~]\nFréquence N°~b~%s rejointe",
    ["leftFrequency"] = "[~g~INFO~s~]\nVous avez quittez votre fréquence",
    ["noItem"] = "[~r~ERREUR~s~]\nVous n'avez pas de radio",
    ["frequencyMaxedOut"] = "[~r~ERREUR~s~]\nLimite maximum atteinte pour la fréquence"
}