---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KraKss.
--- DateTime: 05/07/2023 16:02
---

ESX = exports["es_extended"]:getSharedObject()
PMA = exports["pma-voice"]

cfg = {
    lang = "en",
    maxFrequency = 999, -- a limit over 5000 is not recommended as it can cause lags and who uses more than 5k frequencies anyway ?
    publicFrequencyMaxPlayers = 50,
    privateJobFrequencies = {
        {
            name = "Police Station",
            frequency = 1,
            userLimit = 1,
            jobs = {"police"}
        },
        {
            name = "Police Station",
            frequency = 4,
            userLimit = 15,
            jobs = {"police"}
        },
        {
            name = "Police Station",
            frequency = 5,
            userLimit = 20,
            jobs = {"police"}
        },
        {
            name = "Emergency Medical Services",
            frequency = 2,
            userLimit = 20,
            jobs = {"ambulance"}
        }
    },
    menu = {
        name = "",
        subtitle = "Radio",
        publicSubtitle = "Public stations",
        privateSubtitle = "Job stations",
        displayPageCounter = false,
        desc = "Open the radio menu",
        openKeybind = "F2",
    },
    sql = {
        itemNeeded = true,
        tableName = "items",
        itemName = "radio"
    }
}